const botconfig = require("./botconfig.json");
const Discord = require("discord.js");
const bot = new Discord.Client({ disableEveryone: true });
const ms = require("ms");
const fs = require("fs");


bot.on("ready", async () => {
  console.log(`${bot.user.username} is online and protecting ${bot.guilds.size} servers!`);
  bot.user.setPresence({ status: 'idle', game: { name: 'type ?help for info' }});


bot.on("message", async message => {
  if (message.author.bot) return;
  if (message.channel.type === "dm") return;

  let prefix = botconfig.prefix
  let messageArray = message.content.split(" ");
  let cmd = messageArray[0];
  let args = messageArray.slice(1);

  if (cmd === `${prefix}links`) {
    return message.channel.send("**Applications**\nWebsite: https://nmsassistant.com/\nAndroid: https://play.google.com/store/apps/details?id=com.kurtlourens.no_mans_sky_recipes\niOS: https://apps.apple.com/us/app/id1480287625\nWebApp: https://app.nmsassistant.com/\nDiscord Bot: Coming Soon\n\n**Social**\nTwitter: https://twitter.com/AssistantNMS\nInstagram: https://instagram.com/AssistantNMS\nFacebook: https://facebook.com/AssistantNMS\nSteam Community Page: https://steamcommunity.com/groups/AssistantNMS\nNoMansSky Social: https://nomanssky.social/AssistantNMS");
  }

  if (cmd === `${prefix}test`) {
    let test = new Discord.RichEmbed()
      .setDescription("**This is a test**")
      .setColor("148AFF")
      .addField("__What is your name?__", "My name is the FAQ Bot")
      .addField("__What server are you on?__", "Assistant for NMS");

 return message.channel.send(test);
    }

  if (cmd === `${prefix}international`) {
    let international = new Discord.RichEmbed()
      .setDescription("Information you may need if you are not based in the United States of America:")
      .setColor("#50f442")
      .addField("__**Shipping**__", "Unfortunately, we cannot ship our rewards internationally yet.")
      .addField("__**Game Codes**__", "Most of our gift cards are for U.S. use only. Read the “checkout details” for region information.");

    return message.channel.send("We love our chefs from abroad, and while you may be earning more profit with Salad due to electricity rates, there are some drawbacks for Chefs outside of the U.S. These are:")
      .then(msg => {
        message.channel.send(international)
        .then(msg => {
          message.channel.send("We hope to solve these issues soon with local purchases and global gift cards/codes. Let us know if you have any ideas, we’d love to hear from you!");
        });
    });
  }

  if (cmd === `${prefix}faq`) {
    return message.channel.send("If you can’t find the answers you’re looking for here, try checking out our full FAQ on Freshdesk: https://nmsassistant.freshdesk.com/");
  }

  if (cmd === `${prefix}earnings`) {
    let earnings = new Discord.RichEmbed()
      .setDescription("__**LINKS**__")
      .setColor("#50f442")
      .addField("How much can I earn with Salad?","https://salad.zendesk.com/hc/en-us/articles/360028553551-How-much-can-I-earn-with-Salad-")
      .addField("How can I earn more with Salad?", "https://salad.zendesk.com/hc/en-us/articles/360028257792-How-much-electricity-does-Salad-use-")
      .addField("How does Salad mine cryptocurrency?", "https://salad.zendesk.com/hc/en-us/articles/360028478512-How-can-I-earn-more-with-Salad-");

    return message.channel.send("The money you make with Salad is generated by using your GPU to mine Ethereum (cryptomining). This means that the more powerful Graphics Card you have, the better your earning rate will be. Salad will move away from cryptocurrency based earnings in the future, and transition into Data Processing and High Performance Computing tasks that will earn users much more money for the same processing power.")
      .then(msg => {
        message.channel.send(earnings);
      });
  }

  if (cmd === `${prefix}systemreqs`) {
    let systemreq = new Discord.RichEmbed()
      .setDescription("System Requirements")
      .setColor("#50f442")
      .addField("__**GPU REQUIREMENTS**__", "**Supported 4GB+ VRAM GPU**")
      .addField("__**Operating System**__", " **Windows 7 or Windows 10**")
      .addField("__**CONNECTIVITY**__", "**Working Internet Connection**");

    return message.channel.send(systemreq);
  }

  if (cmd === `${prefix}supportticket`) {
    let supportticket1 = ("To log your support issue and get our team working on it, please copy the format below, fill it in with your bug information, and send it to support to generate a support ticket.");
    let supportticket2 = new Discord.RichEmbed()
      .setDescription("__**Template for a Support Ticket**__")
      .setColor("#50f442")
      .addField("__**Description**__", "- OS\n- Phone\n- App Version")
      .addField("__**Actual Behavior**__", "*Example* \n There is a delay scrolling up the list than there is scrolling down")
      .addField("__**Expected Behavior (Optional)**__", "*Example*\nI should be able to scroll back up at the same rate and responsive that I scrolled down the list")
      .addField("__**Attachments**__", "*When applicable, attach the following:*\n- Logs\n- Video\n- Screenshots");

    return message.channel.send(supportticket1)
      .then(msg => {
        message.channel.send(supportticket2);
      });
  }

  if (cmd === `${prefix}findgpu`) {
    return message.channel.send("If you don’t know what GPU model you have, follow this easy process to find out:\n\n**1.** Search for “Device Manager” in your windows searchbar\n**2.** Open Device Manager (should be under Control Panel)\n**3.** Find the “Display Adapters” tab and double-click it\n**4.** 4. Your GPU model should be displayed there.");
  }

  if (cmd === `${prefix}help`) {
    let help = new Discord.RichEmbed()
      .setDescription("__**List of Commands**__")
      .setColor("#50f442")
      .addField("__**?supportticket**__", "Find out how to get help with errors not covered on the FAQ Bot")
      .addField("__**?systemreqs**__", "View what specs you need to use the iOS or Andriod app")
      .addField("__**?links**__", "View a list of all links related to the NMS Assistant")
      .addField("__**?translation**__", "Help with translating the app!")
      .addField("__**?faq**__", "Look for solutions to a problem you might have!")
      .addField("__**?guides**__", "Help create guides for the app!")
      .addField("__**?freshdesk**__", "Check out our support page!");

    return message.channel.send(help)
      .then(msg => {
        message.channel.send("Thank you for using Assistant for NMS!");
      })
  };

  if (cmd === `${prefix}logs`){
    message.channel.send("To find your Salad logs, first navigate to `%appdata%`. Then you want to go to `roaming` and then into the `Salad` folder. Your logs will be under the file `log.log` which looks like a .txt file!");
  }

  if (cmd === `${prefix}translation`){
    message.channel.send("If you are fluent in a language that isn't already implimented into the app, go to https://nmsassistant.com/tools/translate, or talk to @KhaozTopsy#7865 directly");
  }

  if (cmd === `${prefix}guides`){
    message.channel.send("If you would like to contribute your knowledge of NMS towards the app, head to https://nmsassistant.com/tools/guide and create a guide for us! If approved, this will then be featured in the guides section of the app");
  }

  if (cmd === `${prefix}no-earnings`){
    let noearningsEmbed = new Discord.RichEmbed()
    .setDescription("No Earnings")
    .setColor("#50f442")
    .addField("If your app displays a zero earning rate there are several potential bugs you may be experiencing:", "1. Your Antivirus may be blocking Salad or ethminer.exe\n2. Your Graphics Card drivers may be outdated")
    .addField("These are fixable, and you can find solutions here:", "https://salad.zendesk.com/hc/en-us/categories/360001723991-Troubleshooting")
    .addField("However, if this does not solve your issue then Share Tracking is likely causing the irregularity in your earnings. For more info on share tracking and how it impacts Salad users, either type ?sharetracking or read this helpful guide:", "https://medium.com/@saladchefs/the-salad-guide-to-cryptocurrency-share-tracking-ce97763edf6");
    return message.channel.send(noearningsEmbed);
  }

  if (cmd === `${prefix}freshdesk`){
    let freshdeskEmbed = new Discord.RichEmbed()
    .setDescription("Freshdesk Site")
    .setColor("#50f442")
    .addField("For help with bugs, please go to the Assistant for NMS site found here:", "__**Click the new support ticket button, or read the knowledge base**__\nhttps://nmsassistant.freshdesk.com/")

    return message.channel.send(freshdeskEmbed);
      }
});

bot.login(botconfig.token);
