SET BOT_TOKEN=NjYyNjM3Mjk5NDkzNzY1MTU5.Xg9GQg.HH_1KUgZd2zkpPAjQF1pydw0Wcg
SET BOT_PREFIX=?
SET HEROKU_RELEASE_VERSION=development
SET HEROKU_RELEASE_CREATED_AT=Today

ECHO %BOT_TOKEN%
ECHO %BOT_PREFIX%
ECHO %HEROKU_RELEASE_VERSION%
ECHO %HEROKU_RELEASE_CREATED_AT%

node index.js